### ISSUE TITLE
What is the license for this code?

### ISSUE THREAD

**Issue by bgrainger** [CryptoManiac/Ed25519#1]
CodesInChaos.NaCl, which this was forked from, is public domain: https://github.com/CodesInChaos/Chaos.NaCl/blob/master/License.txt

This repo doesn't explicit state how the code is licensed, so it's possible that it is copyrighted under a more restrictive license.

Could you add a license to the repo that specifies under what terms the code may be redistributed?

**Comment by CryptoManiac** [comment]
I see no reason to put any restriction on this code.
